#!/bin/bash

api() {
	cd "$PWD/cmd/api" || exit
	go build && ./api
}

dapi() {
	API="restful-api"
	docker build . -t ${API}
	docker run -d -p 9001:9001 ${API}
}

ui() {
	cd "$PWD/cmd/ui" || exit
	go build && ./ui
}

app() {
	api&
	ui
}

clean() {
	rm -i "$PWD/cmd/api/api" \
		"$PWD/cmd/api/cfg.yaml" \
		"$PWD/cmd/api/library.db" \
		"$PWD/cmd/ui/ui"
}

dcompose() {
	docker-compose up --build
}

dclean() {
	docker stop restful-api && docker rm restful-api
}

cmds="api app clean dapi dclean dcompose ui"
if [[ -n "$COMP_LINE" ]]; then
	cl="${COMP_LINE##* }"
	for c in ${cmds}; do
		test -z "${cl}" -o "${c}" != "${c#${cl}}" && echo "$c"
	done
	exit
fi

"$@"
